INSERT INTO USER VALUES(101, sysdate(), 'AB');
INSERT INTO USER VALUES(102, sysdate(), 'MAIK');
INSERT INTO USER VALUES(103, sysdate(), 'SERVER');
INSERT INTO USER VALUES(104, sysdate(), 'KYLE');
INSERT INTO POST VALUES(101, "My first post", 101);
INSERT INTO POST VALUES(102, "My second post", 101);